# Generated by Django 3.0.8 on 2020-07-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='avg_audience_score',
            field=models.CharField(max_length=3, verbose_name='Audience Score'),
        ),
        migrations.AlterField(
            model_name='film',
            name='avg_tomatometer',
            field=models.CharField(max_length=3, verbose_name='Tomato_Score'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(max_length=40, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='film',
            name='premier',
            field=models.DateField(verbose_name='Premier date'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
